name: vcamera
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  app_tracking_transparency: ^2.0.1
  camera: ^0.8.1+7
  connectivity: ^3.0.6
  cupertino_icons: ^1.0.2
  device_info: ^2.0.2
  dio: ^4.0.0
  flutter:
    sdk: flutter
  flutter_easyloading: ^3.0.0
  get: 4.3.6
  image_gallery_saver: ^1.6.9
  path: ^1.8.0
  path_provider: ^2.0.2
  shared_preferences: ^2.0.6
  url_launcher: ^6.0.9
  video_player: ^2.1.13

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/images/
